name: Netbird demo
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Netbird Connect
        id: netbird
        uses: Alemiz112/netbird-connect@v1.0.1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          args: '--allow-server-ssh'
      - name: Forced sleep
        run: sleep 30m

